language: c++

compiler:
  - g++
  
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends cmake
  - git clone https://github.com/corehacker/ch-third-party-libs && cd ch-third-party-libs && for file in `ls *.tar.bz2`; do tar xvf $file; done && sudo make glog libevent librdkafka opencv

script: |
  ./autogen.sh
  ./configure
  make
  
notifications:
  email:
    - 123sandy@gmail.com
