language: c++

compiler:
  - g++

before_script:
  - curl -L https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz -o libevent-2.1.8-stable.tar.gz
  - tar xvf libevent-2.1.8-stable.tar.gz && cd libevent-2.1.8-stable && ./configure && make && sudo make install && cd ..

script: |
  ./autogen.sh
  ./configure
  make
  
notifications:
  email:
    - 123sandy@gmail.com
